### ISSUE TITLE
excel utility

### ISSUE THREAD

**Issue by Sambli-Sapahia** [NetzOptimize/pyQA#12]
Report should be displayed with error details in excel sheet

**Comment by thakuravneet** [comment]
We want that feature.

**Comment by Montekkundan** [comment]
@Sambli-Sapahia You can generate excel reports using `--excelreport=report.xls`.
Currently im adding a utility to make your own custom reports using functions. #36 
For most of the cases `--excelreport=report.xls` this will give a promising result, if you want to create your own excel reports, im working on that.

**Comment by Montekkundan** [comment]
If you want to create your own excel reports, with built-in functions (currently working on #36 ) generate a new issue.
